
#####################################################################
# Is git LFS required to run this repository?
#
# This normally remain "Yes", as this prevents inadvertently
# committing large data files
#####################################################################
git_lfs_required: Yes

#####################################################################
# Other required software
#####################################################################
software_required:
  git_lfs: Yes
  gslab_make: Yes
  r: Yes
  stata: Yes
  lyx: Yes
  matlab: No
  latex: No

#####################################################################
# Maximum allowed file sizes
#####################################################################
max_file_sizes:
  file_MB_limit_lfs: 2               # Soft limit on file size (w/ LFS)
  total_MB_limit_lfs: 500            # Soft limit on total size (w/ LFS)  
  file_MB_limit: 0.5                 # Soft limit on file size (w/o LFS)
  total_MB_limit: 125                # Soft limit on total size (w/o LFS)

  