name: template #CHANGE for your project
channels:
  - conda-forge
dependencies:
# Add explicit version numbers to freeze a dependency.
# The format accepts "package=version" or "package>=version"
# with no spaces around the "=" or ">=".
# e.g. - python=3.10.6
  - python 
  - pyyaml 
  - numpy
  - matplotlib
  - gitpython
  - termcolor
  - colorama
  - jupyter
  - linearmodels
  - pandas
  - openpyxl
  # For users of Windows machines, please uncomment the line below if you plan to use `export_excel_tables()` for Excel to PDF conversion.
  # - pywin32

  # - julia

  # - pip
  # - pip: # if there is a package available via pip but not with conda, can import like this.

  - r
  # - r-yaml # import r packages by prepending with "r-"
  # - r-nicheROVER
  - r-tidyverse
